GET http://localhost:3000/products 

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Semen uhuy",
    "image": "img/Semen.jpg",
    "desc": "Semen ini sangat bagus",
    "category": "Furniture",
    "stock": 10,
    "unit_price": 50000,
    "published_at": ""
}

###
GET http://localhost:3000/products/665300bba666dc8c86916233

###
PATCH http://localhost:3000/products/664ea3de33e78e730ca3bfb5
Content-Type: application/json

{
    "name": "Kursi Empat Roda",
    "image": "img/kursi.jpg",
    "category": "Furniture",
    "stock": 5,
    "unit_price": 20000
}

###
DELETE  http://localhost:3000/products/664ef362ad68ccc49738c06a

###
POST http://localhost:3000/products/665300bba666dc8c86916233/reviews
Content-Type: application/json

{
    "user": "Epoy",
    "product_image": "http://example.com/product.jpg",
    "rating": 3,
    "desc": "Aku kasih bintang 3 dulu ya ka, barangnya belum sampai",
    "like": 2,
    "published_at": ""
}

###
DELETE  http://localhost:3000/reviews/664efb281455764c8fa644b1

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "bryanberlandr@example.com",
    "password": "Bbbbbbbb1"
}

###
POST http://localhost:3000/add-admin
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admbuildong"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admbuildong"
}
